version: '3'

services:
  db:
    image: postgres:latest
    container_name: db
    hostname: db
    restart: always
    volumes:
      - postgresdb:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: paper
      POSTGRES_PASSWORD: paper
      POSTGRES_DB: paper
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - 5432:5432

volumes:
  postgresdb: